pipeline {
    agent any
    tools { maven 'Maven3'; jdk 'JDK17' }
    stages {
        stage('Test') {
            steps { sh 'mvn -B clean test' }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'reports/**', allowEmptyArchive: true
        }
    }
}
